FROM squidfunk/mkdocs-material
# see https://github.com/squidfunk/mkdocs-material/blob/master/Dockerfile

## Install plugin https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
RUN pip install mkdocs-awesome-pages-plugin
